port: 8080
format_custom_response: YYYY-MM-DDTHH:mm:ss
auth:
  user: retargetly
  password: retargetly123
  expires: 1200
  secret: RETARGETLY_SECRET
  algorithm: HS256
  format_custom: YYYY-MM-DDTHH:mm:ss
mysql:
  database: retargetly
  user: root
  password: root
  host: localhost
  dialect: mysql
  logging: false
sftp:
  url: input.retargetly.com
  path: /files/
  user: exercises
  password: gQ6gT72I8bmY
  readyTimeout: 60000