port: 8080
auth:
  secret: SECRETO_PARA_ENCRIPTACION
  algorithm: HS256
  expires: 100 #count of seconds
  format_custom: YYYY-MM-DDTHH:mm:ss
mysql:
  database: retargetly
  user: root
  password: root
  host: localhost
  dialect: mysql
sftp:
  url: input.retargetly.com
  path: /files/
  user: exercises
  password: gQ6gT72I8bmY