port: 8080
auth:
  user: Santi
  password: 123
  expires: 1200
  secret: SECRETO_PARA_ENCRIPTACION
  algorithm: HS256
  format_custom: YYYY-MM-DDTHH:mm:ss
mysql:
  database: retargetly
  user: root
  password: root
  host: localhost
  dialect: mysql
  logging: false
sftp:
  url: input.retargetly.com
  path: /files/
  user: exercises
  password: gQ6gT72I8bmY
  readyTimeout: 1000