module.exports = {
    HTTP_CODE_STATUS_OK: 200,
    HTTP_CODE_STATUS_BAD_REQUEST: 400,
    HTTP_CODE_STATUS_UNAUTHORIZED: 401,
    HTTP_CODE_STATUS_NOT_FOUND: 404,
    HTTP_CODE_STATUS_ERROR_INTERNAL: 500
}